const IMAGES = {
    SET_IMAGES : 'SET_IMAGES',
    SEARCH_DATA : 'SEARCH_DATA',
    LOAD_IMAGES: 'LOAD_IMAGES',
    LOAD_IMAGES_SUCCESS: 'LOAD IMAGE SUCCESS',
    LOAD_IMAGES_FAIL: 'LOAD IMAGE FAIL'
};

export default IMAGES;

